name: Terraform Pipeline Practice

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 1. Azure Login
      # --------------------------------------------------
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "464f189d-b28e-4f77-ae60-922c50bc84e9",
              "clientSecret": "mCf8Q~xdJ6OzaGabB9f6tlSs3nD8TtmATz4nJdd9",
              "subscriptionId": "5e0d30bd-3572-4ba7-a892-593061b71738",
              "tenantId": "2f28d638-b1a5-4814-8476-0d4379015748"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6
          terraform_wrapper: false

      # --------------------------------------------------
      # 2. Terraform Init
      # --------------------------------------------------

      - name: Init
        run: terraform init
        
      # --------------------------------------------------
      # 3. Terraform Validate
      # --------------------------------------------------
            
      - name: Validate
        run: terraform validate

      # --------------------------------------------------
      # 4. Terraform Plan
      # --------------------------------------------------

      - name: Plan
        run: terraform plan

      # --------------------------------------------------
      # 5. Terraform Apply
      # --------------------------------------------------

      - name: Apply
        run: terraform apply -auto-approve
